### ISSUE TITLE
FluidTank giving errors on start up

### ISSUE THREAD

**Issue by Retro-boi** [Kotori316/FluidTank#105]
![image](https://user-images.githubusercontent.com/42781539/209861945-e5cd479c-fac3-4d98-81bf-d87c7fe97152.png)
i am trying to play with some friends and i get this error when trying to launch minecraft

and here is the log
[crash-2022-12-28_22.18.11-fml.txt](https://github.com/Kotori316/FluidTank/files/10316020/crash-2022-12-28_22.18.11-fml.txt)

**Comment by Kotori316** [comment]
1. From the crash log, you're using `LargeFluidTank-18.5.1-deobf.jar`, but this file is NOT for end users. It is for mod developers. Please use `LargeFluidTank-18.5.1.jar`, which is main file shown in CurseForge.
2. Please use latest version. I released [18.7.2](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/4074087)
