### ISSUE TITLE
stacker mod dupes all the water x2 any amount that you have

### ISSUE THREAD

**Issue by pearce4** [Kotori316/FluidTank#108]

**Comment by Kotori316** [comment]
What's the "stacker" mod? How to reproduce?

**Comment by pearce4** [comment]
stacker mod lets you stack items farther than what's normle you can get the same result with stacked water buckets 
if the bucket is stacked with anything in it it will duble so if you had x3 it will go x4 and x4 will go to x6
so on and so on
![2023-03-01_18 05 33](https://user-images.githubusercontent.com/97205544/222304359-6fd8d8a0-39e6-4791-8efd-1115a75df1c5.png)

**Comment by Kotori316** [comment]
The mod breaks the stack size assumption for buckets, which should be 1. Almost all mods follow this assumption, so any unexpected behavior may be out of my work.

I'll test the mod to check whether my mod has bugs in handling buckets. Give me detail.
Forge or Fabric? Which Minecraft version? What's exact name of stacker mod? [This one](https://www.curseforge.com/minecraft/mc-mods/stacker)?
