### ISSUE TITLE
Item recipes are not displayed.

### ISSUE THREAD

**Issue by Rogenar** [Kotori316/FluidTank#109]
There is a bug that causes item recipes to not appear in Rei mode. versiyon 1.20.1; largefluidtank-fabric-20.3.1

**Comment by Kotori316** [comment]
![image](https://github.com/Kotori316/FluidTank/assets/28705167/d02e465f-adae-4b87-9ef4-e6e4cd817603)

Are there any problems?

**Comment by Rogenar** [comment]
[latest.log](https://github.com/Kotori316/FluidTank/files/12064577/latest.log)
[rei.log](https://github.com/Kotori316/FluidTank/files/12064578/rei.log)
[rei-issues.log](https://github.com/Kotori316/FluidTank/files/12064582/rei-issues.log)
![ss1](https://github.com/Kotori316/FluidTank/assets/122460325/ee5c6eab-7bf9-400c-97ac-b145f51120d2)

**Comment by Kotori316** [comment]
Thank you for attaching gif and logs, but I'm sorry I can't see detail of recipe from low resolution gif.

I want you to check these.

1. Can you craft tanks in crafting table?
    * If can't, some mods bother to load tank recipe or delete the recipe.
    * As I see the log, it doesn't say anything about tank mod.
2. Could you give me a small list of tanks, where you can get recipe from REI and can't?
    * From your gif, I got some of tanks display the recipe, and others don't.
    * But I can't read the tank name in tooltip.
3. Create new Minecraft environment and install fabric, REI, my mod(and dependencies). Then, will the tank recipes be displayed in REI?

**Comment by Rogenar** [comment]
![ss1](https://github.com/Kotori316/FluidTank/assets/122460325/7c870e2f-eec1-4ca8-8583-729d123ea5b1)
only wooden, gold and silver tanks can be crafted. other tanks cannot be produced. I can't craft other tanks.
[latest.log](https://github.com/Kotori316/FluidTank/files/12080885/latest.log)
[rei.log](https://github.com/Kotori316/FluidTank/files/12080888/rei.log)
[rei-issues.log](https://github.com/Kotori316/FluidTank/files/12080901/rei-issues.log)

**Comment by Rogenar** [comment]
This time I just tried it with the mods below and it shows the recipes. I think it's conflicting with another mod.
![ss2](https://github.com/Kotori316/FluidTank/assets/122460325/fa9e7836-b5c7-4e4a-8819-c43d63f0ed1c)
![ss3](https://github.com/Kotori316/FluidTank/assets/122460325/29f59101-909c-4fea-84cb-f14eed6e712e)
![ss4](https://github.com/Kotori316/FluidTank/assets/122460325/f3c9e3e0-e5eb-4987-9bdf-36b3f2ac107b)

**Comment by Kotori316** [comment]
This might be a problem of your modpack. I'm afraid I can do nothing from my mod because other mods or datapacks delete or conflict with tank recipes.

I'll close this issue, but if you need further discussion to find which mod deletes recipes of tanks, you can reopen this issue.
