### ISSUE TITLE
Fluid Dupe with Thermal Expansion Reservoir

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#12]
Hello =)

Not sure if this is the right place to report the dupe but i will give a try^^
You take some fluid into reservoir and pickup some stone tanks for example. the tanks stack and then set reservoir to 'refilling equipment' mode with sneak+rmb. then you place the stone tanks in the world and every one of them gets the fluid from the reservoir.

Check this video to see what is the problem =)

https://streamable.com/nbros

Minecraft: 1.12.2
Forge .2708
Modpack: My own Modpack: Dungeons, Dragons and Space Shuttles

**Comment by Kotori316** [comment]
This issue page is where you can post everything about this mod and that bug was caused by this mod.

Fixed in 3.9. Thank you for your reporting.
