### ISSUE TITLE
[Suggestion] Compatibility with Evil Craft Sanguinary Environmental Accumulator 

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#14]
Hello =)
I don't know if this can be done from your side. I wanted to ask if there was a way to add the fluid tanks to the Evil Craft Sanguinary Environmental Accumulator so it could be recognized as a valid tank. (Like Endertanks, Drums etc.)

**Comment by Kotori316** [comment]
I've finished implementing it. I'll soon build to generate jar file.

You can use any tanks for Sanguinary Environmental Accumulator but the mod tries to get fluid handler in client side, not in server in which a work is done. My tank returns nothing in client side to avoid errors in connection of vertically connected tanks. If you have any problem, please tell me.

**Comment by Freebi85** [comment]
Thank You so much <3

**Comment by Kotori316** [comment]
Uploaded to CurseForge!
