### ISSUE TITLE
Server crash- net.minecraft.crash.ReportedException: Exception ticking world

### ISSUE THREAD

**Issue by ProsperCraft** [Kotori316/FluidTank#16]
Crash report-
https://gist.github.com/ProsperCraft/d96affc0c1946f226cadd487dfa55d49

I don't think your mod has anything to do with this report as it seems to deal with entities, but I did see in the datapack list

mod:fluidtank (incompatible)

Why would it say that?

[debug.log](https://github.com/Kotori316/FluidTank/files/3359905/debug.log)

**Comment by Kotori316** [comment]
Is it happened in Multiplayer Server or Single player world?
I'll check the structure of Data pack.

**Comment by ProsperCraft** [comment]
Multiplayer server, we test live on a server with a bunch of people, you are welcome to join us.

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
I looked at the crash report and verified it wasn't in the pack at the time.

**Comment by ProsperCraft** [comment]
The server crash was from Silents Gems, now resolved.
