### ISSUE TITLE
Cannot craft tanks except for wooden.  1.14.3 / 6.4

### ISSUE THREAD

**Issue by FraukeS** [Kotori316/FluidTank#17]
Using default configs there are no crafting recipes for the larger tanks,  I tried the recipe from the images but those don't work either.
![fluidtank](https://user-images.githubusercontent.com/24796332/61590983-82eab080-abc0-11e9-8af9-e7fa73a37d07.png)

I'm using minecraft 1.14.3 forge 27.0.50 and fluidtank 6.4

**Comment by Kotori316** [comment]
The recipe is like this picture...
![2019-07-22_12 53 34](https://user-images.githubusercontent.com/28705167/61605296-cb1cd800-ac7f-11e9-96c4-9b1093b3b797.png)

**Comment by Kotori316** [comment]
In Version 6.5
I added support for JEI to allow you to get tank recipe on JEI.
