### ISSUE TITLE
Please update to forge .45 for breaking changes in forge.

### ISSUE THREAD

**Issue by ProsperCraft** [Kotori316/FluidTank#18]
I can't include your mod in my pack update due to breaking changes in forge .45 please update.

**Comment by Kotori316** [comment]
You should write the Minecraft version and why you thought this mod is incompatible with Forge 28.0.45.

The tank works with these mods and Forge 28.0.45.
- BiomesOPlenty-1.14.4-9.0.0.225-universal.jar
- LargeFluidTank-14.6.6.jar
- Scala-library-2.12.8-with-library.jar
- jei-1.14.4-6.0.0.10.jar

**Comment by ProsperCraft** [comment]
Because of this- https://mobile.twitter.com/LexManos/status/1158426171500924930?s=09

And this whish describes how mods behave when loaded an not updated to 45
https://www.minecraftforge.net/forum/topic/74421-1144-forge-28045-mods-randomly-not-loading-properly/

I can test it again, this is one of that mods that tested as a problem in my 20 hour add one mod at a time session.

Crash reports with this issue are useless, a good working mod is always listed as the problem.
