### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException (1.14.4)

### ISSUE THREAD

**Issue by DatrixTHLK** [Kotori316/FluidTank#19]
Hi Kotari316,

Crashing to Desktop. Not sure why.
Minecraft: 1.14.4
Forge (BETA): 28.0.55

Crash: https://gist.github.com/DatrixTHLK/14502536ce3c9c1befbcfcf4b84ba087

**Comment by Kotori316** [comment]
You need to add [library file](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force) to mods folder.
