### ISSUE TITLE
[1.14.4] Minecraft crash before mod loading

### ISSUE THREAD

**Issue by Migmag789** [Kotori316/FluidTank#20]
Hey ! I was using your mod, when I launched the game, the modpack crashed before Minecraft launched. I got this crash report : https://pastebin.com/SS5HadKq

**Comment by Kotori316** [comment]
I uploaded v14.7.1, which supports new condition serialize and new fluid handler system.
https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2774530
