### ISSUE TITLE
[1.14.4] needs language provider kotori_scala - but it is installed.

### ISSUE THREAD

**Issue by ProsperCraft** [Kotori316/FluidTank#21]
![2019-09-21_07 17 30](https://user-images.githubusercontent.com/4427684/65373852-13d11d00-dc40-11e9-8279-bacfbbe33d61.png)

Log-
https://gist.github.com/ProsperCraft/86d550771c2c751bbb23f2325261fd42

Scalable Cats Force-2.13.1-with-library
LargeFluidTank-14.7.6

forge-1.14.4-28.1.10

**Comment by Kotori316** [comment]
As the message tells to you, you need to install the 2.12.9 version of library.
I haven't uploaded any mod that uses 2.13.1 library. This is why the library is alpha.
