### ISSUE TITLE
Graphical error with some other mods

### ISSUE THREAD

**Issue by ct-klein** [Kotori316/FluidTank#22]
Version: v12.4.5

There is a situation that we have been running into for a couple of months now but we have finally pinned it down to the cause.
When using Fluid tanks along with chests from GTCE (GregTech Community Edition), once a tank is filled with a liquid the chests within a certain range will visually glitch out.  The chests will either become invisible or they will visually move to a different location.  Purely a visual issue, the chests are still functional.
We have ruled out shader packs and any resource pack graphics, it can be easily duplicated in a new world adding a few gtce chests of any type, add a fluidtank of any type and then add a liquid to that tank.  Depending on the height of the tank/fluid the chests will disappear or move.
https://imgur.com/0mr5z7x
There are 3 chests in this picture, including the invisible one highlighted.

The mod developer for GTCE took a look at your code and found the issue:
Large fluid tanks call buffer.setTranslation(x, y, z) on global vertex buffer and doesn't bother with restoring defaults

Can you look at this and see if it is something that can be corrected?

Thanks.

**Comment by pyure** [comment]
Yes, please, this.  Our players are big fans of this mod but this one hard-to-isolate issue has been a major thorn for months.

**Comment by Kotori316** [comment]
Added code to reset buffer translation.
`buffer.setTranslation(0, 0, 0)`
Please try [v12.4.6](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2792208).

**Comment by ct-klein** [comment]
I tested this out in a new world using the same process.  Put down chests, put down tanks, fill tanks.  Works like a charm!  This seems to have fixed the issue.  I tried it with multiple different tanks and fluids as well as various GTCE chests.  Thank you very much for the quick response/turnaround on this.

**Comment by Kotori316** [comment]
I'm glad to hear the problem is fixed.
Your and GTCE developer's advice enabled this quick fix. Thank you so much!
If you have some troubles on my mods, feel free to ask on GitHub issue.
