### ISSUE TITLE
Huge Fluidtanks with Empty Faces seem to restrict server start

### ISSUE THREAD

**Issue by TheRealHypo** [Kotori316/FluidTank#27]
Hey, 

very clean Issue panel :) 
But I've got a big one ... 

For several days, rather weeks now we had problems that after server start, the world took a very long time to initialize. Now I've took the time to make a snapshot and check what's the culprit of the long server load. This is tested on a Ryzen 3900X, the actual server runs a much slower CPU, and server start takes about 15min, at that point.

Here the paste of the longest methods on server start. If you are interested in the complete snapshot, pm me.

[profile.csv](https://pastebin.com/YP13Vf0Y)

We now severly reduced the amount of huge stacked Fluidtanks. (we had some funny ones that were 150+ in height) And hope that this resolves the Issue for the moment.

**Comment by Kotori316** [comment]
I uploaded [v12.4.8](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2829112).
Build a tall tower of tank and check there are no lags in loading your world.

Thank you for your reporting. This change is a great improvement of performance.

**Comment by TheRealHypo** [comment]
Tall Tower of Tanks: https://gyazo.com/3113aa1305c878a45b80eccc9cad8b1d 😅 

After replacing mods load time at that point dropped to almost zero ! 👍 
Well couldn't have done it better myself 😂  Spread the word, performance comes back to Minecraft.

I would have never found this out, if I hadn't profiled it for several hours. There is no log output telling what it does at that point. Before pointing at FluidTanks I accused 3 other mods, because of their Log outputs :D
