### ISSUE TITLE
Cant craft the tank

### ISSUE THREAD

**Issue by dbock1989** [Kotori316/FluidTank#28]
Modpack: BoxyWorld 1.2.2
Version MC: 1.14.4
Mod Version: 14.8.6
Forge Version: 28.1.90

Problem: I can craft wood tanks, but that is it. Although the other recipes show (1 tank in each corner of a crafting table) the end product is not obtainable. 

Replicate problem: Join server (if you wish) and try to craft any tank higher than a wooden tank.

Thank you!

**Comment by dbock1989** [comment]
![image](https://user-images.githubusercontent.com/33360899/69488001-1dd6ee00-0e32-11ea-9f06-e1ef30f696f0.png)
![image](https://user-images.githubusercontent.com/33360899/69488005-24656580-0e32-11ea-85cd-4d332cb73a0e.png)

**Comment by Kotori316** [comment]
Try recipes on [this page](https://github.com/Kotori316/FluidTank/wiki/Recipe).
It seems my mod failed to load item tags. I'll update my development environment and work for this issue.

**Comment by dbock1989** [comment]
Thank you! I will try when I get home tonight from work... Ill update when I do.

**Comment by dbock1989** [comment]
So, It doesnt work with those recipes either.  But Im guessing that is suspected.

**Comment by Kotori316** [comment]
I installed BoxyWorld 1.2.3, the latest on 2019/11/25, but tanks can be crafted.
![2019-11-25_15 00 35](https://user-images.githubusercontent.com/28705167/69516457-0d8b5400-0f95-11ea-8aa4-1b7ca8da94b5.png)
![2019-11-25_14 59 21](https://user-images.githubusercontent.com/28705167/69516462-10864480-0f95-11ea-92b5-497c71beedc5.png)

In that environment, tag `forge:stone` refers to these items.
> forge:stone                                   :    17 : explorercraft:slate, explorercraft:marble_polished, minecraft:infested_stone, minecraft:polished_andesite, explorercraft:slate_polished, bluepower:marble, explorercraft:marble, explorercraft:basalt, explorercraft:basalt_polished, minecraft:granite, minecraft:polished_diorite, minecraft:diorite, forbidden_arcanus:dark_stone, bluepower:basalt, minecraft:polished_granite, minecraft:andesite, minecraft:stone

Do you have ways to know which blocks/items are registered as `forge:block` tag?
If yes, please show me.

**Comment by dbock1989** [comment]
So I have to apologize, you are correct. The recipes you sent me do infact work, the reason the did was my fault and human error. 

So Ive come to the conclusion that JEI shows the wrong recipe as you stated previously, and the recipes you sent do work. I really appreciate it! Sorry about the last confusion, I feel bad.
