### ISSUE TITLE
Tanks are dark at night

### ISSUE THREAD

**Issue by Fortist** [Kotori316/FluidTank#3]
https://i.imgur.com/T1dJvk7.png
Despite being filled with lava and lava right next to it, the tanks are dark, only at night.

**Comment by Kotori316** [comment]
Thank you for your report.
The problem was fixed and new version will be released in some days, not today.

![2018-04-16_14 14 02](https://user-images.githubusercontent.com/28705167/38791078-7a4206aa-4180-11e8-9ccb-71075434d956.png)
