### ISSUE TITLE
Unable to add fluid to infinite fluid supplier

### ISSUE THREAD

**Issue by eractnod** [Kotori316/FluidTank#37]
In Version 14.9.0, I am unable to add a fluid other than water to the infinite fluid supplier on a server world.  On a single player world, I can add fluid.  I am trying the diesel fluid from Silent's Mechanisms.  I also tried lava with the same result.  Works fine in single player, but not on a server.  Tried in creative mode as well.

**Comment by Kotori316** [comment]
First of all, I define 2 modes. _CHEAT MODE_ will supply any kind of fluid. _NORMAL MODE_ supplies only water.
In v14.9.0, the block placed by item **got from creative tab** works in _CHEAT MODE_ whatever player's mode is. The supplier got by other ways (crafting, give command, etc) works in _NORMAL MODE_ even if the player is creative.

I uploaded v14.9.1, which has texture change. **CHEAT MODE supplier looks slightly pink.** (NORMAL MODE had no changes and looks white) As same as v14.9.0, supplier mode doesn't have anything with which gamemode players are in.
