### ISSUE TITLE
Only wood tanks available.

### ISSUE THREAD

**Issue by Omnimetatron** [Kotori316/FluidTank#38]
In the latest 1.14 release, only the wood tank has a recipe.

**Comment by Kotori316** [comment]
Could you give me a log file, which is saved in (profile)/logs.
I need “debug.log“ file.

If you want to fix it as soon as possible, use old version.

**Comment by Kotori316** [comment]
In my environment, all tanks can be crafted so I can't reproduce the bug. I hope someone post the debug log that may help me to resolve this issue.
That means I don't fix it for a while.
