### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Play-Kind** [Kotori316/FluidTank#39]
![Screenshot (115)](https://user-images.githubusercontent.com/46108494/73383738-35b36e00-42ca-11ea-9971-f8cccd588c72.png)

**Comment by Kotori316** [comment]
Which version of Forge and mod are you using?

**Comment by Kotori316** [comment]
Also I want you to send me crash report.

**Comment by Play-Kind** [comment]
[crash-2020-01-29_19.08.22-client.txt](https://github.com/Kotori316/FluidTank/files/4134296/crash-2020-01-29_19.08.22-client.txt)

**Comment by Kotori316** [comment]
The crash log doesn't match the screen shot. The picture said a problem in `ClientRegistory` but the log said NPE in InGameScreen.

**Comment by Kotori316** [comment]
Try https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2872218
I rebuild with latest forge for Minecraft 1.15.1
