### ISSUE TITLE
Curseforge tag ambiguity.

### ISSUE THREAD

**Issue by plaguewolf** [Kotori316/FluidTank#40]
Please tag your mod as forge, for ease of use.

**Comment by Kotori316** [comment]
![curseforge_version_forge](https://user-images.githubusercontent.com/28705167/73450454-c3fe2180-43a8-11ea-97b9-8e6cb822c012.png)
I don't like that "Game Version" column shows only Forge. Actually my mod is named with Minecraft version but the above picture will make users confused: _"Which one to download?"_.
