### ISSUE TITLE
Server crashes when trying to pick up fluid tanks

### ISSUE THREAD

**Issue by asoshinsky** [Kotori316/FluidTank#41]
Sometimes server would stop working and crash when I try to pick up a fluid tank with liquid inside. After a couple of crashes, I figured out that it could be astral sorcery perk "spatial manipulation" which allows picked up item to go directly to your inventory. I would have reported it to astral sorcery GidHub, but Large Fluid Tank mod always present at the crash reports.

Modpack: DD&SS version 7.1a

Please, see attached one of the crash reports:
[crash-2020-01-30_21.47.13-server.txt](https://github.com/Kotori316/FluidTank/files/4136438/crash-2020-01-30_21.47.13-server.txt)

**Comment by Kotori316** [comment]
I'll build and upload fixed version.

**Comment by asoshinsky** [comment]
I don't think I follow you. How do I use the java list to pass the harvest event? Thanks for the quick answer thou.

**Comment by Kotori316** [comment]
Built. Try [v12.5.0](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2872707).

----
Commit message is only for developers, not for normal users.
