### ISSUE TITLE
The recipe is not correct for an iron tank.

### ISSUE THREAD

**Issue by Tejasminer** [Kotori316/FluidTank#42]
How do I correct the recipe. 
This is 1.15

**Comment by Kotori316** [comment]
Could you give me these items?
* log file, `debug.log` and `latest.log`, saved in `(profile)/logs`.
* Screen shot of crafting table with the recipe and JEI (if you're using).

The first one is the most important. I've got same recipe errors from some users but I can' figure out what is wrong. I need log file to know what's happened.
