### ISSUE TITLE
Emerald Tank Incorrectly Interacting with Blood Magic's Blood Altar

### ISSUE THREAD

**Issue by Styxx-Anaxkolasi** [Kotori316/FluidTank#47]
I'm using an stacked tank system with various kinds of tanks in the Dungeons, Dragons, and Space Shuttles modpack, and it's been working fine. 
I recently got an Emerald tank, and when I tried to add it to the bottom of the stack, it drained all the Life Essence I had stored, and replaced it with 500 mB of Blood. I can add Life Essence to an Emerald Tank with a bucket or a cell, but I cannot pipe it in. I'm using Thermal Dynamics Fluiducts, and up until now have had no issues. 
I also tried it with only the emerald tank, and had the same issue.

**Comment by Styxx-Anaxkolasi** [comment]
I just tried prefilling the emerald tank with Life Essence and reconnecting it, and that worked, but when I made the initial connection it didn't and you should at least know about it

**Comment by Kotori316** [comment]
I'm sorry I don't know the detail of Blood Magic, so I can't get what you did and what happened.
I want to ask you some details.
1. Life Essence is red fluid that comes from mod "Blood Magic"?
2. What's "Blood"? The red fluid which comes from mod "Evil Craft"?
3. Just placing emerald tank at the bottom of tanks will not cause such problem. See my poor picture below. Your title contains "Blood Alter" but the body doesn't mention the alter.
![tank_I47_1](https://user-images.githubusercontent.com/28705167/81169099-38adb100-8fd3-11ea-96a6-ccb7f56dd1ee.png)

Give me more detail of what you did with some screenshots.
Thank you for your reporting.

**Comment by Styxx-Anaxkolasi** [comment]
The Blood Magic Blood Altar is just the mod's storage for Life Essence, which is the red liquid in Blood Magic. You use a sacrificial dagger to fill the altar and you can use it for changing items by putting them in the top of the Altar. The blood it replaced it with was EvilCraft's blood. 
![image](https://user-images.githubusercontent.com/64876998/81228904-849d2d80-8fb4-11ea-9d5c-4c6827338534.png)
Above is a picture of my current blood altar

![image](https://user-images.githubusercontent.com/64876998/81228928-98489400-8fb4-11ea-8f81-6640053204bf.png)
You can attach pipes to the bottom of the blood altar to pump blood out, which is pictured here, and I have them going into a variety of tanks. When I attached the Emerald tank to the bottom, there wasn't very much life essence left, probably only about 50 buckets or so, and I was pumping life essence in from the altar when I upgraded it, which might have had an effect. 

I've been unable to reproduce what happened, so it might just have been a one off thing.
I'm also playing on my friend's server, so there's also potential for it to be a serverside problem and not a mod problem. 
If there's any more information you need I can try to get it to you

Thanks for your time
