### ISSUE TITLE
Tanks are consumed in recipes that require buckets of fluid

### ISSUE THREAD

**Issue by NillerMedDild** [Kotori316/FluidTank#49]
Some crafting recipes allow inputting a tank where a bucket of some fluid would be, to enable batch-crafting of the recipe. For this to work, the tank must implement `getContainerItem`, otherwise the tank will be consumed by the first craft of the recipe.

I found this issue when using one of your Fluid Tanks to craft Treated Wood from Immersive Engineering - The tank was consumed even though it had 4000 mb of Creosote Oil in it.

Also reported to the IE tracker here: https://github.com/BluSunrize/ImmersiveEngineering/issues/3873

**Comment by Kotori316** [comment]
In 1.14.4? I think this problem happens in all version of my mod so I'll implement container code for 1.12.2, 1.14.4, 1.15.2.

Do you know some recipes that use bucket as fluid container? I need to check my code works fine.
* 1.12.2 -> IC2 recipe to create cooling cell
* 1.14.4 -> IE recipe to create Treated Wood
* 1.15.2 -> ???

**Comment by NillerMedDild** [comment]
I'll try to find a fluid recipe in 1.15.2 :)

**Comment by Kotori316** [comment]
![2020-05-25_19 10 47](https://user-images.githubusercontent.com/28705167/82803623-d18d6900-9ebb-11ea-9988-0bdf1d0132a2.png)
After crafted treated wood

[v14.9.8](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2965332)

**Comment by NillerMedDild** [comment]
Awesome, thanks!
