### ISSUE TITLE
Lots of Fatal Errors in log

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Kotori316/FluidTank#50]
I have been going through the log files for my mod pack I am developing and now debugging. MultiMC put the following message in the latest.log file

> MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.0
- LargeFluidTank-15.2.9

Here is a portion of the log file showing fatal errors that appear to come from Large Fluid Tanks. Both Pastebin and GitHub would not accept the full latest.log file, so here is a portion:

https://pastebin.com/PrT4qk3u

**Comment by Kotori316** [comment]
Added code to suppress NPE. [v15.3.0](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/2971474)

I don't know where the log comes from. The message means there is CATTile in the server but no tile in client. That's very strange.
