### ISSUE TITLE
Tank Capacities and Fluid Rendering [1.15.2]

### ISSUE THREAD

**Issue by papaworld** [Kotori316/FluidTank#52]
Hi, thank you for such a great mod... very helpful.

The capacities of 2 tanks appear to be duplicated... Iron and Lead at 256kmb. Is it possible the Iron tank should be 128kmb?

The rendering of some fluids show the tank filling from top to bottom and emptying from bottom to top... liquid floating in air type of thing. This occurs in a couple of mods and their liquids. Mekanism brine and liquid lithium for instance.

MC - 1.15.2
FML - 31.2.9
Tanks - all versions - 15.3.0

ThanX

**Comment by Kotori316** [comment]
The rendering is intended, as these liquid are registered as "Gaseous" fluid. See attached text, "[fluid.txt](https://github.com/Kotori316/FluidTank/files/4802581/fluid.txt)". In 1.12.2, BluidCraft registers their gas(hot oils and more) as gaseous fluid and tanks from BC shows the gas filled from top to bottom.
BTW, gas in Mekanism is registered as their own gas type, not fluid by forge. Then, my tanks can't hold gas by Mekanism.

I'm testing for changing tank capacity to find problems of compatibility.

**Comment by Kotori316** [comment]
![2020-06-19_14 36 29](https://user-images.githubusercontent.com/28705167/85100186-793b5400-b23a-11ea-84f8-6cf4fc8b4381.png)
Iron Tank(capacity: 128 Buckets) crafted by 4 filled tin tanks(64 B). I placed the tank, then the tank has only 128 B of lava, though tooltip said 256 B.

It's impossible to change capacity of tank for 1.15.2 version, but I think your idea is good so I'll make changes for 1.16 version.

**Comment by papaworld** [comment]
Super... thank you
