### ISSUE TITLE
Fabric version unable to load on dedicated server

### ISSUE THREAD

**Issue by hadn69** [Kotori316/FluidTank#55]
It crashes in the datapack loading phase and cannot proceed. My server log is attached.
[latest.log](https://github.com/Kotori316/FluidTank/files/5192843/latest.log)

**Comment by Kotori316** [comment]
The mod was trying to call client only method from server instance.

I fixed the bug and uploaded [v16.0.3](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/3052985).
