### ISSUE TITLE
[1.16.4] Fairy Lights incompatibility crash

### ISSUE THREAD

**Issue by RandomCanadian** [Kotori316/FluidTank#64]
When [Fairy Lights](https://www.curseforge.com/minecraft/mc-mods/fairy-lights) is used with FluidTank it will cause a crash when placing down a tank. It's reproducible and has been tested with only those two mods enabled. I've included a crashlog.
[crash-2020-11-17_06.26.40-client.txt](https://github.com/Kotori316/FluidTank/files/5551660/crash-2020-11-17_06.26.40-client.txt)

**Comment by Kotori316** [comment]
It seems my mods failed to load mixin system. It's not compatibility issue.
Downgrade forge will avoid crash.

I'll continue to research this problem.

**Comment by noncom** [comment]
There's some tested info that the latest Forge version that doesn't crash is 35.0.15

**Comment by pau101** [comment]
Err, I am curious to why you mixin `LazyOptional`, that is incredibly invasive for something which seems like it should not be necessary.

**Comment by Kotori316** [comment]
I wanted to change the status(valid or invalid) of LazyOptional from inside of supplier.

Anyway I fixed the code not to depend on mixin codes. [v16.0.8](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/3115568)
