### ISSUE TITLE
Datapack issues since 16.0.8

### ISSUE THREAD

**Issue by cyberpunkbln** [Kotori316/FluidTank#66]
Hello,

only a little issue. My datapack from 16.0.6/7 don't functioned 100% in 16.0.8.

First i deactivate the old recipes from wood tank

fluidtank/recipies/tank_wood.json and tank_wood_easy.json => 0  bytes.

The i implement the harder recipie:

harder-recipes/recipies/tank_wood.json

In the older versions tank_wood.json will be nulled and deactivated and only my new harder recipie will be used. Since 16.0.8 he don't null the original recipie and take both recipies original and harder.

?

**Comment by Kotori316** [comment]
It's not allowed to remove recipe by replacing with 0 byte file. As you see, you'll get `Couldn't parse data file fluidtank:tank_wood from fluidtank:recipes/tank_wood.json` or some errors.
It's fine to override the recipe with your own recipe. Save it to fluidtank/recipies/tank_wood.json.

If you want to disable recipe, put this to fluidtank/recipies/tank_wood.json
```json
{
  "type": "fluidtank:crafting_grade_up",
  "tier": "silver",
  "sub_item": {
    "tag": "forge:ingots/silver"
  },
  "conditions": [
    {
      "type": "forge:false"
    }
  ]
}
```
(The recipe type or silver doesn't matter. **`forge:false` in condition will prevent this file being loaded.**)

BTW, you can disable all tank recipe by changing **`RemoveRecipe` in config to true**.

Also, in my environment with these mods, **datapacks correctly override recipes**. As you know, I was working on an issue with mixin and I made no change in recipe system(I'm using vanilla system modified by forge).
|Number | ModID         | Name                |    Version | File Name                          | Class                             |
|-----: | :------------ | :------------------ | ---------: | :--------------------------------- | :---------------------------------|
|     1 | minecraft     | "Minecraft"         |     1.16.4 | forge-1.16.4-35.0.18-client.jar    | java.lang.String                  |
|     2 | theoneprobe   | "The One Probe"     | 1.16-3.0.6 | theoneprobe-1.16-3.0.6.jar         | mcjty.theoneprobe.TheOneProbe     |
|     3 | fluidtank     | "FluidTank"         |     16.0.8 | LargeFluidTank-16.0.8.jar          | com.kotori316.fluidtank.FluidTank |
|     4 | forge         | "Forge"             |    35.0.18 | forge-1.16.4-35.0.18-universal.jar | net.minecraftforge.common.ForgeMod|
|     5 | kotori_dumper | "Dumper"            |     16.3.1 | Dumper-1.16.1-16.3.1.jar           | com.kotori316.dumper.Dumper       |
|     6 | jei           | "Just Enough Items" |   7.6.0.58 | jei-1.16.4-7.6.0.58.jar            | mezz.jei.JustEnoughItems          |

**Comment by cyberpunkbln** [comment]
Ah okay Thx. Seems like zerobyte-jsons only work 15,x and lower. The HarderFluidTank-Datapack ist the first that i use in 1.16:). Functioned very well with the forge condition. Thx.
