### ISSUE TITLE
Mod Crashes Immediately After Placing Tank

### ISSUE THREAD

**Issue by JotaKujo** [Kotori316/FluidTank#67]
The mod seems to load fine, there's no issues when loading in but whenever someone attempts to place one of the tanks down it crashes their game and locks them out of the server, :0
Version: 1.16.4
crash log: https://pastebin.com/QubrjNbg

**Comment by Kotori316** [comment]
<strong>DON'T GET MOD FROM ILLEGAL SITE</strong>

You should not get files from sites listed [here](https://stopmodreposts.org/sites.html). My files are available only in [CurseForge](https://www.curseforge.com/minecraft/mc-mods/largefluidtank), GitHub Release and my Google Drive.

Download latest version from proper site.
