### ISSUE TITLE
[Fabric] [Rending Bug] Fluid not displayed in large tanks

### ISSUE THREAD

**Issue by milkev** [Kotori316/FluidTank#69]
Fluids in the larger tanks do not render a layer at the bottom until it reaches a certain % of the max.
It would be nice if there was the smallest layer rendered if the fluid amount is at a point its not displayed at all. This will make tanks easier to read at a glance, and without the use of HWYLA, you will actually know whats in the tank.

**Comment by Kotori316** [comment]
Do you mean fluids in tank are not shown like pictures in [this page](https://github.com/Kotori316/FluidTank/wiki/Tank)?
Recently, I'm not working on Fabric version 1.16, so it may have changes in rendering system.

**Comment by milkev** [comment]
Fluids usually render as normal, however in the larger tanks there seems to be a certain amount of fluid the tank must be holding before any fluid is rendered.
If you fill it up enough, fluid does start to render, however with large tanks like the star tank, you need a huge amount of liquid before you even get the small layer at the bottom of the tank.
This is easily reproducable by placing a star tank, and placing a few buckets of fluid in it, or a few hundred buckets of fluid...
I suspect this is present on forge as well, however I can't test as I do not use forge 1.16

**Comment by Kotori316** [comment]
OK. I misunderstood your first comment.
You think it'll be nice if star tank holding just 1 bucket shows its content, now it doesn't show water or lava until the tank holds 1% of capacity.

Now the rendering is intended (working completely as I wrote in the source code), but can be improved.

**Comment by Kotori316** [comment]
[v16.1.0](https://www.curseforge.com/minecraft/mc-mods/largefluidtank-fabric/files/3177394)

**Comment by milkev** [comment]
sorry i didnt end up being able to check it myself until today.
Fluids straight up no longer show in the tanks. Tested only using fabric api, fluid tanks, and its dependencies on 1.16.5.
the silver and wood tanks are full of water, the star tank has a few buckets of water in it. lava yielded the same result.
![2021-01-28_21 11 11](https://user-images.githubusercontent.com/22010128/106230847-a1fed100-61ad-11eb-89ed-4cd57b321e1e.png)
![2021-01-28_21 10 32](https://user-images.githubusercontent.com/22010128/106230849-a2976780-61ad-11eb-8463-a0b3d03af9af.png)

**Comment by Kotori316** [comment]
It was a problem related with graphic mode, "Fabulous" and translucent textures. Changing to fancy will resolve this problem, but I upload new file to change render mode to Cutout when Fabulous and Translucent when fancy or fast.
