### ISSUE TITLE
[1.16.5] [Compat] Fluid pump stops working on reload of world

### ISSUE THREAD

**Issue by wieselkatze** [Kotori316/FluidTank#72]
### Description of the issue:
Whenever the world is reloaded, the tank doesn't allow IE's fluid pump to pump out fluid any more. Only re-placing the pump helps this.
This does not happen with IE's own devices, nor with Create's tanks.
Somehow, the Create pump does still manage to extract fluid from Fluid Tanks after a reload, though.
As this is compat-related, I don't know where exactly to post this, but I suppose it has to do with how the fluid tank initializes on world loading, breaking IE's pump, which probably only does one check for fluid inventories and then quits working (just a guess, obviously).

### Versions & Modlist
Running on Forge 1.16.5-36.0.13, LargeFluidTank-16.1.2 and ImmersiveEngineering 1.16.5-4.2.1-131
[Mod list](https://gist.github.com/wieselkatze/d27d8454990b7adb75cd793d341af409)

**Comment by Kotori316** [comment]
I found a code that may relate this issue. I forgot to mark abandoned the dummy tank used before tank connection is loaded.
I'll find the solution and fix, but it takes a bit log.

**Comment by Kotori316** [comment]
May be fixed in 16.1.3

**Comment by wieselkatze** [comment]
@Kotori316 Seems to work now, many thanks!
