### ISSUE TITLE
[Enhancement] Bucket Mode / Reservoir

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#76]
Hello 😃 
I was wondering if it would be possible to implement some kind of bucket mode for the fluid tanks (1.16.5) that would allow players to use it as a kind of reservoir when right clicking on fluids.

Cheers 🍺

**Comment by Kotori316** [comment]
Implemented. See #77 for some pictures. It can drain fluids from the world and fill tanks. It can't place fluids holding in the reservoir into the world(I didn't implement to prevent bugs). It shows the content in inventory but doesn't in FPS or TPS view because of some troubles in rendering.

**Comment by Freebi85** [comment]
Thank you very much! <3 This makes the already amazing tanks even more fantastic. 😃
