### ISSUE TITLE
Crafting "Issue" with custom recipes.

### ISSUE THREAD

**Issue by Freebi85** [Kotori316/FluidTank#78]
Hey there :)

When adding custom recipes with KubeJS and/or Crafttweaker which includes large fluid tanks i got a dupe bug with the tanks (when fluids are inside)

I'm not sure if it's just an issue with how custom recipes are set up and this is not being handled properly; because your custom recipes work fine when liquids are used in them.

Small Video:
https://user-images.githubusercontent.com/42634622/110207408-97f28100-7e83-11eb-8706-2e12cb738b43.mp4

Cheers

**Comment by Kotori316** [comment]
I don't know the recipe mods deeply, so I would like to ask some questions.
1. Is it possible to modify recipes via datapack, not by the mods. I controlled the remaining items (the items left on the crafting tables, such as empty bucket and tank) by defining own recipe class. From datapack, you can set `"type": "fluidtank:reservoir_recipe"` to create proper recipe but I can't modify remaining items if you use normal recipe class (Shaped recipe and Shapeless recipe)
2. Do you come up with a recipe that _consumes_ water/lava bucket (does not leave empty bucket on crafting table) added by CraftTweaker or KubeJS? You'll find that empty bucket is left if you create a recipe that use water bucket and use the recipe. The same thing happened to the reservoir recipe.

**Comment by Kotori316** [comment]
I found a way to add custom type recipe with KubeJS. The example in [this page](https://mods.latvian.dev/books/kubejs/page/recipeeventjs) adds custom type recipe in line 72-82.
I'll make the reservoir recipe more flexible and write an example of new reservoir recipe.

**Comment by Kotori316** [comment]
Uploaded v16.1.6

This is KubeJS code to add reservoir recipe. This is for iron reservoir. Change `tier` for other reservoirs(wood, stone).
In `sub` arrays, you can use any ingredients including tags(e.g. #forge:gold_ingot).
```javascript
event.custom({
  type: 'fluidtank:reservoir_recipe',
  tier: 'iron',
  sub: [
    Ingredient.of('minecraft:bucket').toJson()
  ]
})
```
In this case, the recipe is Iron Tank + 1x bucket.

This is json for stone reservoir recipe.
```json
{
  "type": "fluidtank:reservoir_recipe",
  "tier": "stone",
  "sub": [
    {
      "item": "minecraft:bucket"
    }
  ]
}
```
You can change `sub` to modify recipe.

**Comment by Freebi85** [comment]
Thank you very much for the fast reply! Didn't know about the   "type": "fluidtank:reservoir_recipe", thingy.
The custom script works as intended.

Cheers 🍺
