### ISSUE TITLE
Cannot modify recipe

### ISSUE THREAD

**Issue by itsdinkd** [Kotori316/FluidTank#85]
Please add or use vanilla recipe datapack generation.

Due to being such a bizarre method for recipe and what I assume to be java controlled, no one can edit the recipe. This makes it hard to balance out these tanks due to how easily it is to get the star tank.. 

I cannot use KubeJS to modify the recipe, and I cannot even create a datapack to modify the recipe 

```json
{
  "type": "fluidtank:crafting_grade_up",
  "tier": "star"
}
```

Not sure what to do about this.

**Comment by Kotori316** [comment]
How do you try to modify the recipe if I add vanilla system as you said? Even if the recipe json seems like vanilla one, you need to create a datapack (not meaning your own namespace) to change ingredients in the recipe.

---
You can override the recipe in order not to work. Then, add your recipe.

There's no need to "modify" recipe. Just remove old recipes and add new ones.

**Comment by itsdinkd** [comment]
You're right. I'll just make my own shaped recipe in the datapack

**Comment by itsdinkd** [comment]
> How do you try to modify the recipe if I add vanilla system as you said? Even if the recipe json seems like vanilla one, you need to create a datapack (not meaning your own namespace) to change ingredients in the recipe.

KubeJS btw is how you would create a recipe w/o creating a datapack.

The recipes are completely broken. you put the individual tanks in a crafting table, and no output shows. and this is using the mods default recipe. 

~~Going to remove the mod from Another Quality Modpack 2. If you ever create the recipes the standard way, please let me know and I will add it back. thank you.~~
Figured out a hack
