### ISSUE TITLE
Fabric Version Crashes

### ISSUE THREAD

**Issue by GhostlyII** [Kotori316/FluidTank#87]
I've been receiving internal server crashes while playing on a server and all my crash reports point to this mod. Not sure if it's something on my end or a java error?

Here's a crash report with the java error.

https://pastebin.com/S5nTv6gn

**Comment by Kotori316** [comment]
Were you doing something to the tank? (inserting fluid or draining from tank)
Then, the latest version will fix.

**Comment by GhostlyII** [comment]
I was draining the tank with a Thermal Generator from TechReborn. I guess that caused issues?

**Comment by Kotori316** [comment]
Null check is done before rendering, but, in this case, a packet from server which tells the change of content to client changed `TileTank$Tank#box` to null between null check and rendering in client. (This is my mistake of implementing)

I added some codes to avoid this interception.
