### ISSUE TITLE
FluidTanks crash occured

### ISSUE THREAD

**Issue by DatrixTHLK** [Kotori316/FluidTank#9]
Hi,

Minecraft: 1.12.2
forge: 14.23.4.2759
Large Fluid Tank: 2.9

Crash Log:  https://paste.dimdev.org/unusozudah.mccrash

When starting up Minecraft this crash occurred. Do I need some sort of coremod?

**Comment by Kotori316** [comment]
Thank you for your report.

I uploaded 3.0. Please try it.
If it isn't uploaded yet, download jar file from [here](https://drive.google.com/drive/folders/1YDorkQXeQbekJ33b-YqHs3HmhC4NL0OG?usp=sharing).

1. I use `Optional.Interface` [annotation](https://github.com/Kotori316/FluidTank/blob/master/scala/com/kotori316/fluidtank/tiles/TileTankNoDisplay.scala#L23) to avoid this crash, but crash occured. Do you know mods that provide BuildcraftAPI? I know you don't use BC, but then `Optional.Interface` works and this crash can't happen.
2. Why isn't my mod signed? In my environment, crash log shows like this.  
	| UC    | fluidtank                                 | 2.9                      | LargeFluidTank-2.9.jar                               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |  
Your log shows this.  
       | U     | fluidtank                         | 2.9                      | LargeFluidTank-2.9.jar                              | None                                     |  
617... is signature of my mods. I think it's strange.

**Comment by DatrixTHLK** [comment]
I will try out the new version. Thanks for the quick response time.

1. The only mod and Plugins that use the Buildcraft API or used to anyways is/was/were Buildcraft  and it's associated plugins.. I'm not familiar with optional.Interface, but if I had to guess, it would be that the Fluid tank can or is able to interface or work with machines, but doesn't have to.

2. I'm really not sure why your mod would be unsigned or signed in the first place. It's possible that the crash occurred just as the mod was being put through the process when starting up Minecraft. 

I'm a bit confused really. Thanks again, though. I appreciate it.

**Comment by Kotori316** [comment]
I'm sorry for making you confused.

The signature shows the file was definitely made by the author, Kotori316 in this case.  No signature may mean the file is changed by someone or I made some mistakes when building jar file. I think you got mod file from CurseForge and I'm sure this is safe.

Anyway, I hope that crash is fixed and you can enjoy your Minecraft life.

**Comment by DatrixTHLK** [comment]
Ah, I see. No worries, I'm easily confused. That makes it much simpler for me to understand. Thanks again I'm going to try it out now

**Comment by DatrixTHLK** [comment]
It works now. Thanks for the fix.
