### ISSUE TITLE
how to with furnace?

### ISSUE THREAD

**Issue by KraftLarence** [Kotori316/FluidTank#95]
Hello and thank you for your time and consideration. I currently run 16.5 and enjoy the mod very much. My concern is that I am unaware of how to feed what is in the tanks into the back of a furnace. I have been able to use it with so many other mods for other things and it is extraordinary. Thank you for your patience.

**Comment by Kotori316** [comment]
I'm not sure what I understand is correct, so let me ask a question.
Do you want to use Lava tank as fuel of a furnace like Lava Bucket?

**Comment by KraftLarence** [comment]
In a sense yes, but only sort of. Thank you for your response. It may sound silly but I cant get the tank to auto feed smokers, furnaces, etc. However, I use it exclusively with the immersive rail and engineering mods. It auto feeds diesel and crude oil so well seamless even.  I can't get it to put a buckets worth of lava in the burner. I have used various pipes from pretty fluid to the immersive pack to hoppers. I still want the grind and I enjoy the gathering so much, but I don't like using the tinker construct mod and its the only one that works to that end. I know that there are many things about modding that I do not understand. Moreover, I appreciate the input in trying to help me.

**Comment by KraftLarence** [comment]
It started by placing the tank with a dropper and some observers it'll feed but it puts the entire contents of the tank in the furnace regardless to how many buckets in the tank and uses it as one bucket. I've been able to replicate this three times but even that is not consistent. It does cause crashing at times, yet its stable in use with immersive R and E.

**Comment by Kotori316** [comment]
I don't know much about Immersive Engineering and Immersive Railroading, so I want to make sure what the furnace is and how the furnace consumes fuel.
I thought the furnace is vanilla one, and it consumes the item in GUI as fuel. So I had to register the tanks as fuel.

But, you're talking something different from my knowledge, such as auto feeding of Oil (as fuel?). How do the tanks work with Dropper and Observer? Can you tell me more detail of your machines with picture?

**Comment by KraftLarence** [comment]
![image](https://user-images.githubusercontent.com/104725246/174427729-b7415aa2-4209-4069-aa4d-f7b55ef2be6d.png)

this refills the steam engine with water successfully.
![image](https://user-images.githubusercontent.com/104725246/174427763-4406852d-42f9-4178-b9b8-4b06d93a66aa.png)
this has been the model that has worked for one load but it does cause crashes. 2 observers on side next to down dropper into chest tank at that point it'll do one lava buckets worth but empty entire tank or it wont do anything most of the time. I have had a lava block exit the front of the furnace too.
![image](https://user-images.githubusercontent.com/104725246/174427878-ff650d1b-ac2f-4051-9ab5-a60bcab3cc8b.png)
This holds and distributes all fluids wonderfully. I have also used it with the ultimate car mod.

**Comment by KraftLarence** [comment]
![image](https://user-images.githubusercontent.com/104725246/174428342-024d8581-0d06-4af3-a418-6105af50763a.png)
This method a hundred percent of the time but I don't like tinkers at much. That is why I was trying to find a reach around with a nilla furnace.

**Comment by KraftLarence** [comment]
yes

**Comment by KraftLarence** [comment]
so was there no to convert without an empty bucket?

**Comment by Kotori316** [comment]
I wrote some codes to use tanks as furnace Fuel for 1.19 (it can be ported to 1.16.5).
Watch [this video](https://youtu.be/adap9nqdzec). Does this help you?
EDIT: In this video, vanilla milk is used as Fuel. It is just prepared for this video. So, it's not a content of tank mod.

If this is not what you want to do, tell me, please.

I understand that the first picture with train, which supplies Water from tank.
Second is... Do you mean that you want to move just one bucket(1000 mB) to the Empty Bucket in Furnace?
Third one seems to show a machine from IE, but I don't know what this is.
For 4th one with Smeltery, I think you want to move some amount of fluid with IE pump, right?

I'm sorry for my misunderstanding, but I want to improve the mod as possible as I can.

**Comment by KraftLarence** [comment]
Thank you so much for your help and your patience this helps a lot. All of the work you do is very much appreciated.

**Comment by KraftLarence** [comment]
That is exactly what I meant honestly I didn't know if I was asking it right. Oh and the third machine is a pumpjack its really handy. you need IE but it came in mod Immersive petroleum. Are you saying I can run the 1.19 mod on 1.16.5 just checking?

**Comment by KraftLarence** [comment]
![image](https://user-images.githubusercontent.com/104725246/174470524-2aed2b6f-83a5-401a-8a8c-5acd0a5dc135.png)

This one?

**Comment by Kotori316** [comment]
Could you wait a moment until I release new version for 1.16.5?
The 1.19 version doesn't work in 1.16.5.
I meant that this feature can be ported to 1.16.5 from 1.19 easily because I can use almost same code in 1.16.5, which is in development side, not in player side.

**Comment by Kotori316** [comment]
Uploaded [v16.1.9](https://www.curseforge.com/minecraft/mc-mods/largefluidtank/files/3838627).

**Comment by KraftLarence** [comment]
Thank you so much. I really like your mod. The applications for its use are
so various. I encourage your progress. I know that the mods for Minecraft
are always growing and changing. I feel this mod is as essential as getting
the JEI mod. As the game and mods grow in development I know that your mod
will only be relied on even more.

**Comment by Kotori316** [comment]
Could you wait a moment until I release new version for 1.16.5?
The 1.19 version doesn't work in 1.16.5.
I meant that this feature can be ported to 1.16.5 from 1.19 easily because
I can use almost same code in 1.16.5, which is in development side, not in
player side.

2022年6月19日(日) 16:29 KraftLarence ***@***.***>:
